### ISSUE TITLE
There's gotta be a better way to keep track of bugs/features than post-its...

### ISSUE THREAD

**Issue by maya-shankar** [CarolineLaw/allowanceTracker#3]
**What**

> Right now I’m just putting stuff on post its to keep track of things we’d like to add to the app.

From Caroline's [blog post](https://spudsdevblog.wordpress.com/2021/12/22/6-allowance-tracker-a-super-simple-android-app/).

**Potential Solutions**

The Issues tab would be better, no?

**Comment by SpudLaw** [comment]
I just saw this!!! That would be great idea :D thank you!!!!!!!
